Improve page titles
tramlinehq/tramline pull request #701
Opened 2024-12-20 05:28 UTC by majjikishore007

**Closes:** https://github.com/tramlinehq/site/issues/580

**Because:**  
We want our page titles to be more meaningful than "ORG_NAME | Tramline."

**This Addresses:**  
- Adds an I18n-based setup in `en.yml` so we have more user-friendly, localized page titles.
- Centralizes all title logic for making updates and maintenance simpler

Quick demo :  
https://www.loom.com/share/b4c3ad5e3e2d4961b3e045d7bb23756d?sid=a88ee43a-c3c4-4296-9019-10fa8b8bbbb1

2024-12-23 06:10 UTC, kitallis commented
@majjikishore007 Thank you for this PR, give us a few days this week to review it.

2024-12-26 13:02 UTC, nid90 requested changes
The PR overall looks good, @majjikishore007! Thank you. 🙇‍♀️ 

I have noted a slight improvement at one place, and some missing locales.

I will merge this once those are resolved!

2024-12-27 05:13 UTC, majjikishore007 commented on app/controllers/application_controller.rb
> +  def set_page_name
Hi @nid90, the requested changes were done thanks

2024-12-27 05:14 UTC, majjikishore007 commented on config/locales/en.yml
> +          edit: "Rule Edit"
added the controllers to the config

2024-12-27 06:42 UTC, nid90 commented
@majjikishore007 Looks good! There is a minor lint issue that can be fixed by running `just lint`. I will merge this once all the checks pass! ⭐

2024-12-27 07:46 UTC, majjikishore007 commented
@nid90, I have fixed the lint issues thanks

2024-12-27 08:20 UTC, nid90 approved these changes

2024-12-27 09:17 UTC, kitallis commented
@majjikishore007 Your PR is ready to be merged, but before we do so, we'd like you to sign our [Contributor Agreement](https://drive.google.com/file/d/1-sE783R8eAn9TGwkDSrjqhZvxQfvVec5/view?usp=sharing). It's a standard [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) based on the Clojure/Eclipse CA.

Please fill and send to contributors AT tramline DOT app

2024-12-27 11:46 UTC, majjikishore007 commented
@kitallis I have signed and sent the document to the mentioned email address. do let me know if anything needs to be added more, thanks

2024-12-27 13:56 UTC, merged